fix(sandside): #114 avoid override dns servers
Override DNS server cause error at startup only in production
java.lang.IllegalStateException: failed to create a new resolver

refs #113
fix #114